load('banana_entrogy.mat','banana_entropy');
a=banana_entropy(:,2);
b=banana_entropy(:,3);
c=banana_entropy(:,4);
d=banana_entropy(:,5);
e=banana_entropy(:,6);
f=banana_entropy(:,7);
g=banana_entropy(:,8);
h=banana_entropy(:,9);
i=banana_entropy(:,10);
j=banana_entropy(:,11);
k=banana_entropy(:,12);
l=banana_entropy(:,13);
m=banana_entropy(:,14);
n=banana_entropy(:,15);
o=banana_entropy(:,16);
p=banana_entropy(:,17);
q=banana_entropy(:,18);
r=banana_entropy(:,19);
s=banana_entropy(:,20);
t=banana_entropy(:,21);
u=banana_entropy(:,22);
v=banana_entropy(:,23);
w=banana_entropy(:,24);
xx=banana_entropy(:,25);
y=banana_entropy(:,26);
z=banana_entropy(:,27);
aa=banana_entropy(:,28);
ab=banana_entropy(:,29);
ac=banana_entropy(:,30);
ad=banana_entropy(:,31);
%ºá×ø±ê
x=banana_entropy(:,1);

plot(x,a,'-s',x,b,'-s',x,c,'-s',x,d,'-s',x,e,'-s',x,f,'-s',x,g,'-s',x,h,'-s',x,i,'-s',x,j,'-s',x,k,'-s',x,l,'-s',x,m,'-s',x,n,'-s',x,o,'-s',x,p,'-s',...
    x,q,'-s',x,r,'-s',x,s,'-s',x,t,'-s',x,t,'-s',x,u,'-s',x,v,'-s',x,w,'-s',x,xx,'-s',x,y,'-s',x,z,'-s',x,aa,'-s',x,ab,'-s',x,ac,'-s',x,ad,'-s');hold on
xlabel('½Ç¶È');
ylabel('ìØ');