load('banana_energy.mat','banana_enerpy');
a=banana_energy(:,2);
b=banana_energy(:,3);
c=banana_energy(:,4);
d=banana_energy(:,5);
e=banana_energy(:,6);
f=banana_energy(:,7);
g=banana_energy(:,8);
h=banana_energy(:,9);
i=banana_energy(:,10);
j=banana_energy(:,11);
k=banana_energy(:,12);
l=banana_energy(:,13);
m=banana_energy(:,14);
n=banana_energy(:,15);
o=banana_energy(:,16);
p=banana_energy(:,17);
q=banana_energy(:,18);
r=banana_energy(:,19);
s=banana_energy(:,20);
t=banana_energy(:,21);
u=banana_energy(:,22);
v=banana_energy(:,23);
w=banana_energy(:,24);
xx=banana_energy(:,25);
y=banana_energy(:,26);
z=banana_energy(:,27);
aa=banana_energy(:,28);
ab=banana_energy(:,29);
ac=banana_energy(:,30);
ad=banana_energy(:,31);
%横坐标
x=banana_energy(:,1);

plot(x,a,'-s',x,b,'-s',x,c,'-s',x,d,'-s',x,e,'-s',x,f,'-s',x,g,'-s',x,h,'-s',x,i,'-s',x,j,'-s',x,k,'-s',x,l,'-s',x,m,'-s',x,n,'-s',x,o,'-s',x,p,'-s',...
    x,q,'-s',x,r,'-s',x,s,'-s',x,t,'-s',x,t,'-s',x,u,'-s',x,v,'-s',x,w,'-s',x,xx,'-s',x,y,'-s',x,z,'-s',x,aa,'-s',x,ab,'-s',x,ac,'-s',x,ad,'-s');hold on
xlabel('角度');
ylabel('能量');